data class Post(
    val id : Int = 0,
    val toId : Int = 0,
    val fromId : Int = 0,
    val createdBy: Int = 0,
    val date : Int = 1649592702,
    val text : String = "Крайне интересная запись",
    val replyOwnerId : Int = 0,
    val replyPostId : Int = 0,
    val friendsOnly : Boolean = false,
    val comments : Comments = Comments(),
    val copyright: Copyright = Copyright(id),
    val likes: Likes = Likes(),
    val repostsCount : UInt = 0u,
    val userReposted : Boolean = false,
    val viewsCount : UInt = 0u,
    val postType : String = "post",
    val signerId : Int = 0,
    val canPin : Boolean = true,
    val canDelete : Boolean = true,
    val canEdit : Boolean = true,
    val isPinned : Boolean = true,
    val marked_as_ads : Boolean = true,
    val isFavorite : Boolean = false,
    val donut: Donut = Donut(),
    val postponedId : Int = 0,
    val attachments : Attachments? = null
) {
}